name: Update Graph

on:
  schedule:
    - cron: '*/15 * * * *'  # Executa a cada 15 minutos
  workflow_dispatch:  # Permite execução manual

permissions:
  contents: write  # Concede permissão de escrita para o conteúdo do repositório
  id-token: write #gpt pediu pra adicionar isso, vamos ver se ajuda

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false  # Não persiste as credenciais padrão

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.9'  # Especifica o uso do Python 3.9

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Script
      env:
        WU_API_KEY: ${{ secrets.WU_API_KEY }}
      run: |
        python atualizaCSV.py

    - name: Commit and Push Changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git add graph.png weather_data.csv
        git commit -m 'Atualização automática do gráfico e dados' || echo "Nada para commitar"
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
