name: Update Graph

on:
  schedule:
    - cron: '8 0 * * *' 
    - cron: '23 0 * * *'
    - cron: '38 0 * * *' 
    - cron: '53 0 * * *'
    - cron: '8 1 * * *' 
    - cron: '23 1 * * *'
    - cron: '38 1 * * *' 
    - cron: '53 1 * * *'
    - cron: '8 2 * * *' 
    - cron: '23 2 * * *'
    - cron: '38 2 * * *' 
    - cron: '53 2 * * *'
    - cron: '8 3 * * *' 
    - cron: '23 3 * * *'
    - cron: '38 3 * * *' 
    - cron: '53 3 * * *'
    - cron: '8 4 * * *' 
    - cron: '23 4 * * *'
    - cron: '38 4 * * *' 
    - cron: '53 4 * * *'
    - cron: '8 5 * * *' 
    - cron: '23 5 * * *'
    - cron: '38 5 * * *' 
    - cron: '53 5 * * *'
    - cron: '8 6 * * *' 
    - cron: '23 6 * * *'
    - cron: '38 6 * * *' 
    - cron: '53 6 * * *'
    - cron: '8 7 * * *' 
    - cron: '23 7 * * *'
    - cron: '38 7 * * *' 
    - cron: '53 7 * * *'
    - cron: '8 8 * * *' 
    - cron: '23 8 * * *'
    - cron: '38 8 * * *' 
    - cron: '53 8 * * *'
    - cron: '8 9 * * *' 
    - cron: '23 9 * * *'
    - cron: '38 9 * * *' 
    - cron: '53 9 * * *'
    - cron: '8 10 * * *' 
    - cron: '23 10 * * *'
    - cron: '38 10 * * *' 
    - cron: '53 10 * * *'
    - cron: '8 11 * * *' 
    - cron: '23 11 * * *'
    - cron: '38 11 * * *' 
    - cron: '53 11 * * *'
    - cron: '8 12 * * *' 
    - cron: '23 12 * * *'
    - cron: '38 12 * * *' 
    - cron: '53 12 * * *'
    - cron: '8 13 * * *' 
    - cron: '23 13 * * *'
    - cron: '38 13 * * *' 
    - cron: '53 13 * * *'
    - cron: '8 14 * * *' 
    - cron: '23 14 * * *'
    - cron: '38 14 * * *' 
    - cron: '53 14 * * *'
    - cron: '8 15 * * *' 
    - cron: '23 15 * * *'
    - cron: '38 15 * * *' 
    - cron: '53 15 * * *'
    - cron: '8 16 * * *' 
    - cron: '23 16 * * *'
    - cron: '38 16 * * *' 
    - cron: '53 16 * * *'
    - cron: '8 17 * * *' 
    - cron: '23 17 * * *'
    - cron: '38 17 * * *' 
    - cron: '53 17 * * *'
    - cron: '8 18 * * *' 
    - cron: '23 18 * * *'
    - cron: '38 18 * * *' 
    - cron: '53 18 * * *'
    - cron: '8 19 * * *' 
    - cron: '23 19 * * *'
    - cron: '38 19 * * *' 
    - cron: '53 19 * * *'
    - cron: '8 20 * * *' 
    - cron: '23 20 * * *'
    - cron: '38 20 * * *' 
    - cron: '53 20 * * *'
    - cron: '8 21 * * *' 
    - cron: '23 21 * * *'
    - cron: '38 21 * * *' 
    - cron: '53 21 * * *'
    - cron: '8 22 * * *' 
    - cron: '23 22 * * *'
    - cron: '38 22 * * *' 
    - cron: '53 22 * * *'
    - cron: '8 23 * * *' 
    - cron: '23 23 * * *'
    - cron: '38 23 * * *' 
    - cron: '53 23 * * *'
  workflow_dispatch:  # Permite execução manual

permissions:
  contents: write  # Concede permissão de escrita para o conteúdo do repositório
  id-token: write #gpt pediu pra adicionar isso, vamos ver se ajuda

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false  # Não persiste as credenciais padrão

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.9'  # Especifica o uso do Python 3.9

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Script
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        python atualizaCSV.py

    - name: Commit and Push Changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git add graph.png weather_data.csv
        git commit -m 'Atualização automática do gráfico e dados' || echo "Nada para commitar"
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
